title = "D-Web.net"
baseURL = "https://dweb.net"
tags = [
  "blockchain",
  "infrastructure",
  "web3",
  "crypto",
  "deepin",
  "filecoin",
  "cosmos",
]
languageCode = "en-US"
config = "config.toml"
theme = "osprey"
canonifyURLS = true
googleAnalytics = ""
disqusShortname = "tomanistor"
disableKinds = [
  "taxonomy",
  #  "taxonomyTerm",
] # This theme does not currently use "tag" and "category" taxonomies

[Params]
tagline = "D-Web.net"
author = "Michael Maurakis"
description = "Full-stack web developer and UI/UX enthusiast based in San Antonio, TX."
logoBig = "/images/dweb-logo.png"
logoSmall = "/images/dweb-logo.png"
favicon = "/images/dweb-logo.png"
opengraphImage = "/images/osprey.png"
email = "info@dweb.net"
googleTagManager = ""
customCSS = false

# Social media links in footer
twitter = "dwebtechsa"
linkedin = "d-webtechnologies"
github = "d-web-net"
#facebook = ""

# Copyright and theme author credit in footer
copyright = true
credit = false

# Cache busting of static resources (additional set up required)
cacheBustCSS = true
cacheBustJS = true

# Code highlighting with highlight.js
highlightJS = true
highlightJSStyle = ""  # For custom highlight.js styles, add your /path/to/styles/default.css
highlightJSScript = "" # For custom highlight.js languages config, add your /path/to/highlight.pack.js

# Choose either Formspree contact form or Basin contact form
ajaxFormspree = false
ajaxFormspreeGold = false
ajaxBasin = "https://usebasin.com/f/ef92294fe619"

# Lazy loading with lazysizes
lazyloading = true

[[menu.main]]
name = "About"
url = "/#about"
weight = 1
[[menu.main]]
name = "Projects"
url = "/#work"
weight = 2
[[menu.main]]
name = "Blog"
url = "/#blog"
weight = 3
[[menu.main]]
name = "Contact"
url = "/#contact"
weight = 4
